apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: PGPASSWORD
              value: "admin123"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
            - mountPath: /var/lib/postgresql/mount
              name: postgresdata
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-data-pv-claim